name: ReleaseBot

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install native libs
        run: sudo apt-get install -y libkrb5-dev libgsasl-dev
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          version: "23.2"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        working-directory: ./
        run: echo ${{ github.sha }} > Release.txt
      - name: Compile
        run: cargo build --features hdfs,jemalloc,allocator-analysis --release
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Release.txt
            LICENSE
            target/release/uniffle-worker
          draft: true