name: ReleaseBot

on:
  push:
    branches:
      - "test_release.1.*"

jobs:
  linux-x86_64:
    name: Build Snapshot
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: prompt/actions-commit-hash@v3
        id: commit

      - uses: ScribeMD/rootless-docker@0.2.2
        if: steps.cache.outputs.cache-hit != 'true'

      - uses: ScribeMD/docker-cache@0.5.0
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          key: docker-centos7-${{ hashFiles('dev/centos7/Dockerfile') }}

      - name: Build
        run: |
          sed -i 's/docker-compose -f/docker compose -f/g' ./release.sh
          ./release.sh

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: uniffle-worker
          path: target-docker/release/uniffle-worker
