name: ReleaseBot

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: centos:7
    steps:
      - name: Install development tools
        run: |
          yum update -y
          yum groupinstall -y "Development Tools"
          yum install -y krb5-devel libgsasl-devel

      - name: Install Protoc
        # 注意：在 CentOS 7 容器中安装 Protoc 可能需要不同的步骤
        run: |
          PROTOC_ZIP=protoc-3.19.4-linux-x86_64.zip
          curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.19.4/$PROTOC_ZIP
          unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
          unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
          rm -f $PROTOC_ZIP
          export PATH=/usr/local/bin:$PATH

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: echo ${{ github.sha }} > Release.txt

      - name: Compile
        run: |
          source $HOME/.cargo/env
          cargo build --features hdfs,jemalloc,allocator-analysis --release

      - name: Release CentOS 7 Binary
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Release.txt
            LICENSE
            target/release/uniffle-worker
          draft: true